using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ChatAPI.Migrations
{
    /// <inheritdoc />
    public partial class AddMediaAndDeletedMessages : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
{
    migrationBuilder.Sql(@"
        ALTER TABLE ""Messages"" ADD COLUMN IF NOT EXISTS ""MediaBase64"" text;
        ALTER TABLE ""Messages"" ADD COLUMN IF NOT EXISTS ""MediaType"" text;
        ALTER TABLE ""Messages"" ADD COLUMN IF NOT EXISTS ""FileName"" text;
        ALTER TABLE ""Messages"" ADD COLUMN IF NOT EXISTS ""DeletedForEveryone"" boolean NOT NULL DEFAULT false;

        CREATE TABLE IF NOT EXISTS ""DeletedMessages"" (
            ""Id"" integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            ""MessageId"" integer NOT NULL,
            ""UserId"" integer NOT NULL,
            CONSTRAINT ""FK_DeletedMessages_Messages_MessageId"" FOREIGN KEY (""MessageId"") REFERENCES ""Messages""(""Id"") ON DELETE CASCADE,
            CONSTRAINT ""FK_DeletedMessages_Users_UserId"" FOREIGN KEY (""UserId"") REFERENCES ""Users""(""Id"") ON DELETE CASCADE
        );

        CREATE INDEX IF NOT EXISTS ""IX_DeletedMessages_MessageId"" ON ""DeletedMessages""(""MessageId"");
        CREATE INDEX IF NOT EXISTS ""IX_DeletedMessages_UserId"" ON ""DeletedMessages""(""UserId"");
    ");
}
        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "DeletedMessages");

            migrationBuilder.DropColumn(
                name: "FileName",
                table: "Messages");

            migrationBuilder.DropColumn(
                name: "MediaBase64",
                table: "Messages");

            migrationBuilder.DropColumn(
                name: "MediaType",
                table: "Messages");
        }
    }
}
